---
# CIS 2.x — Deshabilitar servicios innecesarios

- name: Deshabilitar y detener servicios innecesarios (CIS 2.x)
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - avahi-daemon
    - cups
    - isc-dhcp-server
    - isc-dhcp-server6
    - slapd
    - nfs-server
    - rpcbind
    - rsync
    - vsftpd
    - xinetd
    - telnet
    - talk
  failed_when: false
